
export default {
  login: `${process.env.REACT_APP_API_PROTOCOL}://espworkforceapi.test.tglserver.net/api/login`,
  logout: `${process.env.REACT_APP_API_PROTOCOL}://espworkforceapi.test.tglserver.net/api/user/logout`,
  userDetail: `${process.env.REACT_APP_API_PROTOCOL}://espworkforceapi.test.tglserver.net/api/user/details`,
  api: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/`,
  createUser: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User`,
  userSearch: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/SearchUsers`,
  user: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/`,
  userLoginHistory: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/loginhistory`,
  refreshToken: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/Account/RefreshToken`,
  updateUserDetail: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/UpdateUserDetail`,
  updateDataProtection: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/UpdateDataProtection`,
  addUserNote: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/AddNotes`,
  webSubscriptions: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/GetWebSubscriptionsWithUserCount`,
  publications: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/Publication/GetPublicationsWithUserCount`,
  professionMembershipSubscriptions: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/GroupRegistrationType/GetGroupRegistrationTypesWithUserCount`,
  lookUpNumber: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/LookUpCustomer`,
  importHistory: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/ImportUser/GetImportUserHistory`,
  importHistoryPublications: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/Publication/search?productTypeId=6`,
  importHistoryProfession: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/GroupRegistrationType`,
  importUsers: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/ImportUser`,
  importHistoryData: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/ImportUser/GetImportUserHistoryData`,
  importUsersFileUpload: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/ImportUser/ImportUserUpload`,
  publicationSearch: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/Publication/search`,
  productType: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/ProductType`,
  circulationSearch: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/CirculationStatus/search`,
  subscription: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/Subscription`,
  updateAllSubscription: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/UpdateAllUserSubscriptions`,
  addProfessionMembershipSubscriptions: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/GroupRegistration`,
  getManageSubscriptionUserList: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/GetUserBySubscriptionId`,
  syncUser: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/Sync`,
  makeAdmin: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/Subscription/MakeAdmin`,
  removeSubscription: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/Subscription/RemoveUserSubscription`,
  addUserToSubscription: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/User/MapUserwithSubscription`,
  getBulletinList: `${process.env.REACT_APP_API_PROTOCOL}://${process.env.REACT_APP_API_ENV}${process.env.REACT_APP_API_ENDPOINT}/Bulletin/GetUserBulletin/`,
  changePassword: `${process.env.REACT_APP_API_PROTOCOL}://espworkforceapi.test.tglserver.net/api/user/changepassword`,
};
